spring:
  application:
    name: payflow
  datasource:
    url: jdbc:postgresql://localhost:5433/payflow
    username: payflow
    password: securepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop  # Might have to change for 'validate' later
    show-sql: true
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

server:
 port: 8080